 title: Simple container traffic with failure.
 description: In this scenario we create a container, run some traffic on it and validate outcome. We are failing the validation check on purpose.
 env:
    schema:
      initialObjects:
        key1: SharedMap
        key2: SharedMap
 stages:
  - task-1:
    id: 1
    name: Here is the task 1
    package: "ticker"
    params:
      totalTicks: 5
      msBetweenTicks: 1000
      msgOnTick: "I am ticking every 1000ms"
      msgEndTicking: "I done ticking"
  - task-2:
    id: 2
    name: Here is the task 2
    package: "ticker"
    params:
      totalTicks: 1
      msBetweenTicks: 500
      msgOnTick: "I am ticking every 500ms"
      msgEndTicking: "I am also done ticking"
  - task-3:
    id: 3
    name: Create azure client
    package: azureFactory
    params:
      type: local
      endpoint: http://localhost:7070
      userId: SomeUserId;
      userName: SomeName;
    out: $(client1)
  - task-4:
    id: 4
    name: Create container
    package: containerFactory
    params:
      client: $(client1)
      schema: ${schema}
    out: $(container1)
  - task-5:
    id: 5
    name: Create traffic
    package: containerTrafficRunner
    params:
      client: $(client1)
      docId: $(container1)
      schema: ${schema}
      actions:
      - action1:
        action: set
        target: key1
        key: a
        value: test1
      - action2:
        action: set
        target: key2
        key: b
        value: test2
      flushAfterAction: true
      flushAfterRun: true
  - task-6:
    id: 6
    name: Validate traffic
    package: containerTrafficValidator
    params:
      client: $(client1)
      docId: $(container1)
      schema: ${schema}
      actions:
      - action1:
        action: get
        target: key1
        key: a
        expectedVal: test1
      - action2:
        action: get
        target: key2
        key: b
        expectedVal: test400
